import {
  Disaster,
  SOSRequest,
  Shelter,
  Hospital,
  Resource,
  RoadSegment,
  Alert,
  AIInsight,
  CascadeGraph,
  DashboardKPIs,
} from "@/types";

export const MOCK_ACTIVE_DISASTER: Disaster = {
  id: "dis-odisha-cyclone-2026",
  name: "Cyclone VARUN & Mahanadi Basin Inundation",
  type: "cyclone",
  status: "active",
  severity: "critical",
  center: { lat: 19.8135, lng: 85.8312 },
  radiusKm: 140,
  affectedPopulation: 284500,
  estimatedDamageInr: 420000000,
  startedAt: "2026-10-07T04:00:00Z",
  updatedAt: "2026-10-08T13:45:00Z",
  description:
    "Category 4 severe cyclonic storm making landfall along the Odisha coastline with continuous 135 km/h winds, triggered river surge in Daya and Bhargavi river distributaries.",
  zones: [
    {
      id: "zone-puri-coastal",
      name: "Puri Coastal Belt",
      severity: "critical",
      population: 94000,
      evacuatedCount: 68500,
      coordinates: [
        [85.78, 19.78],
        [85.92, 19.82],
        [85.88, 19.91],
        [85.72, 19.86],
        [85.78, 19.78],
      ],
    },
    {
      id: "zone-konark-delta",
      name: "Konark Marine Delta",
      severity: "high",
      population: 52000,
      evacuatedCount: 39000,
      coordinates: [
        [85.95, 19.85],
        [86.12, 19.92],
        [86.08, 20.02],
        [85.91, 19.96],
        [85.95, 19.85],
      ],
    },
    {
      id: "zone-brahmagiri-wetland",
      name: "Brahmagiri Lagoon Inflow",
      severity: "high",
      population: 43000,
      evacuatedCount: 29500,
      coordinates: [
        [85.6, 19.72],
        [85.75, 19.77],
        [85.7, 19.85],
        [85.55, 19.8],
        [85.6, 19.72],
      ],
    },
  ],
};

export const MOCK_KPIS: DashboardKPIs = {
  totalAffected: 284500,
  totalEvacuated: 137000,
  activeSOSCount: 14,
  criticalSOSCount: 5,
  resolvedSOSCount: 82,
  deployedNDRFTeams: 18,
  activeSheltersCount: 34,
  shelterOccupancyRate: 78.4,
  hospitalICUCapacityRate: 84.1,
  safeRoadCoveragePct: 62.5,
  aiConfidenceScore: 94.2,
};

export const MOCK_SOS_REQUESTS: SOSRequest[] = [
  {
    id: "sos-001",
    requesterName: "Balaram Sahoo",
    phone: "+91 98452 11920",
    location: { lat: 19.8055, lng: 85.8201 },
    address: "Ward 4, Near Jagannath Marine Drive, Puri",
    type: "rescue",
    urgency: "critical",
    status: "in_progress",
    peopleCount: 6,
    specialNeeds: ["elderly", "infant"],
    description: "Water level reached first floor roof. 2 elderly persons unable to walk. Electric current snapping.",
    createdAt: "2026-10-08T12:10:00Z",
    assignedTeam: "NDRF Team Bravo-3 (Inflatable Boat)",
    estimatedReachMinutes: 8,
  },
  {
    id: "sos-002",
    requesterName: "Sunita Das",
    phone: "+91 97711 44023",
    location: { lat: 19.832, lng: 85.845 },
    address: "Balighai Fisherman Colony",
    type: "medical_emergency",
    urgency: "critical",
    status: "assigned",
    peopleCount: 4,
    specialNeeds: ["medical_urgent"],
    description: "Pregnant woman experiencing labor complications. Road cut off by falling casuarina trees.",
    createdAt: "2026-10-08T12:25:00Z",
    assignedTeam: "ODRAF Medical Evac-2",
    estimatedReachMinutes: 14,
  },
  {
    id: "sos-003",
    requesterName: "Ramesh Jena",
    phone: "+91 94370 88219",
    location: { lat: 19.841, lng: 85.795 },
    address: "Brahmagiri High School Perimeter",
    type: "food",
    urgency: "high",
    status: "verified",
    peopleCount: 18,
    specialNeeds: ["children"],
    description: "Community hall surrounded by water. No drinking water for 14 hours. 8 kids below 10 years.",
    createdAt: "2026-10-08T11:45:00Z",
    assignedTeam: null,
    estimatedReachMinutes: null,
  },
  {
    id: "sos-004",
    requesterName: "Priyanka Mohapatra",
    phone: "+91 82490 33811",
    location: { lat: 19.865, lng: 85.862 },
    address: "Gop Block, Daya River bank village",
    type: "rescue",
    urgency: "high",
    status: "received",
    peopleCount: 3,
    specialNeeds: [],
    description: "River embankment breaching 200m away. Need urgent evacuation before dark.",
    createdAt: "2026-10-08T13:05:00Z",
    assignedTeam: null,
    estimatedReachMinutes: null,
  },
  {
    id: "sos-005",
    requesterName: "Chitta Ranjan",
    phone: "+91 91234 56789",
    location: { lat: 19.811, lng: 85.815 },
    address: "Pentakota Fishermen Slum",
    type: "shelter",
    urgency: "medium",
    status: "resolved",
    peopleCount: 12,
    specialNeeds: [],
    description: "Temporary shelter roof damaged. Moved to Zilla Parishad Multipurpose Cyclone Shelter.",
    createdAt: "2026-10-08T09:15:00Z",
    assignedTeam: "District Relief Squad 4",
    estimatedReachMinutes: 0,
  },
];

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: "sh-puri-01",
    name: "Puri Zilla Parishad Multipurpose Cyclone Shelter",
    location: { lat: 19.818, lng: 85.838 },
    address: "Near Collectorate, VIP Road, Puri",
    capacity: 1200,
    currentOccupancy: 1040,
    status: "open",
    facilities: ["Drinking Water RO", "Diesel Genset (125kVA)", "Paramedic Post", "Sanitation Blocks", "Baby Food"],
    contactPhone: "+91 6752 222100",
    distanceKm: 1.4,
  },
  {
    id: "sh-konark-02",
    name: "Konark Sun Temple Community Relief Centre",
    location: { lat: 19.889, lng: 86.094 },
    address: "Tourism Complex, Konark",
    capacity: 800,
    currentOccupancy: 610,
    status: "open",
    facilities: ["Food Distribution", "Emergency Power", "Satellite Phone Link", "First Aid"],
    contactPhone: "+91 6758 236820",
    distanceKm: 8.7,
  },
  {
    id: "sh-brahmagiri-03",
    name: "Alarnath High School Shelter",
    location: { lat: 19.795, lng: 85.698 },
    address: "Brahmagiri Market Road",
    capacity: 650,
    currentOccupancy: 650,
    status: "full",
    facilities: ["Water Tankers", "Solar Lanterns", "Community Kitchen"],
    contactPhone: "+91 6752 278144",
    distanceKm: 12.3,
  },
  {
    id: "sh-satyabadi-04",
    name: "Bakul Bana Government College Shelter",
    location: { lat: 19.945, lng: 85.823 },
    address: "Sakhigopal, Satyabadi Block",
    capacity: 1500,
    currentOccupancy: 780,
    status: "open",
    facilities: ["Helipad Access", "Mobile Hospital Unit", "Food Ration Stock", "Dormitories"],
    contactPhone: "+91 6752 234190",
    distanceKm: 14.5,
  },
];

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: "hosp-01",
    name: "District Headquarter Hospital (DHH) Puri",
    location: { lat: 19.816, lng: 85.829 },
    address: "Grand Road, Puri",
    totalBeds: 350,
    availableBeds: 28,
    icuBeds: 40,
    availableIcuBeds: 4,
    powerStatus: "generator_backup",
    waterLevelMm: 120,
    floodRiskLevel: "medium",
    oxygenDaysRemaining: 4.5,
    ambulanceCount: 9,
    contactNumber: "+91 6752 223555",
  },
  {
    id: "hosp-02",
    name: "Sub-Divisional Hospital Pipili",
    location: { lat: 20.115, lng: 85.832 },
    address: "Bhubaneswar-Puri NH 316",
    totalBeds: 120,
    availableBeds: 35,
    icuBeds: 12,
    availableIcuBeds: 6,
    powerStatus: "grid_operational",
    waterLevelMm: 0,
    floodRiskLevel: "low",
    oxygenDaysRemaining: 7.0,
    ambulanceCount: 4,
    contactNumber: "+91 6758 240212",
  },
  {
    id: "hosp-03",
    name: "Community Health Centre (CHC) Brahmagiri",
    location: { lat: 19.799, lng: 85.702 },
    address: "Brahmagiri, Puri District",
    totalBeds: 60,
    availableBeds: 2,
    icuBeds: 4,
    availableIcuBeds: 0,
    powerStatus: "generator_backup",
    waterLevelMm: 450,
    floodRiskLevel: "critical",
    oxygenDaysRemaining: 1.2,
    ambulanceCount: 1,
    contactNumber: "+91 6752 278050",
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "res-boat-01",
    name: "Gemini Inflatable Rescue Boat B-14",
    type: "rescue_boat",
    status: "deployed",
    location: { lat: 19.805, lng: 85.819 },
    assignedTo: "NDRF 03 Battalion",
    capacity: "8 persons / 750 kg",
    fuelPct: 82,
    lastPing: "2 mins ago",
  },
  {
    id: "res-team-02",
    name: "NDRF Bravo-3 Specialized Flood Squad",
    type: "rescue_team",
    status: "deployed",
    location: { lat: 19.812, lng: 85.825 },
    assignedTo: "Puri Coast Zone",
    capacity: "14 Diver Specialists",
    fuelPct: 100,
    lastPing: "1 min ago",
  },
  {
    id: "res-heli-01",
    name: "IAF Mi-17 V5 Airdrop Unit",
    type: "helicopter",
    status: "available",
    location: { lat: 20.244, lng: 85.817 },
    assignedTo: "Biju Patnaik AFS Base",
    capacity: "4000 kg Relief Supplies",
    fuelPct: 95,
    lastPing: "5 mins ago",
  },
  {
    id: "res-water-01",
    name: "Mobile RO Water Filtration Tanker (10kL)",
    type: "water_tanker",
    status: "in_transit",
    location: { lat: 19.842, lng: 85.831 },
    assignedTo: "PHED Emergency Cell",
    capacity: "10,000 Liters",
    fuelPct: 68,
    lastPing: "Just now",
  },
  {
    id: "res-med-01",
    name: "Rapid Response Medical Team (RRMT Alpha)",
    type: "medical_team",
    status: "deployed",
    location: { lat: 19.817, lng: 85.83 },
    assignedTo: "DHH Puri Triage Center",
    capacity: "4 Doctors + 6 Nurses",
    fuelPct: 100,
    lastPing: "4 mins ago",
  },
];

export const MOCK_ROADS: RoadSegment[] = [
  {
    id: "road-nh316",
    name: "NH-316 (Bhubaneswar - Puri Expressway)",
    status: "open",
    severity: "low",
    coordinates: [
      [85.82, 20.24],
      [85.83, 20.12],
      [85.83, 19.95],
      [85.83, 19.82],
    ],
    notes: "Traffic monitored; slow near Pipili bypass.",
  },
  {
    id: "road-marine-dr",
    name: "Puri - Konark Marine Drive",
    status: "blocked",
    severity: "critical",
    coordinates: [
      [85.84, 19.8],
      [85.95, 19.85],
      [86.09, 19.89],
    ],
    notes: "3.2km road inundated by 1.2m tidal surge; fallen electrical poles.",
  },
  {
    id: "road-sh13",
    name: "SH-13 (Brahmagiri - Satapada Link)",
    status: "under_water",
    severity: "high",
    coordinates: [
      [85.7, 19.8],
      [85.6, 19.74],
      [85.45, 19.68],
    ],
    notes: "Submerged under 80cm flood water from Chilika lagoon overflow.",
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alt-01",
    title: "Mahanadi & Daya River Level Flash Red Warning",
    message: "River Daya gauge at Kanas reached 11.2m (0.8m above Danger Level). Low-lying habitations must evacuate immediately.",
    severity: "critical",
    hazardType: "flood",
    issuedAt: "2026-10-08T13:30:00Z",
    source: "Central Water Commission (CWC) & ASPIRE AI",
  },
  {
    id: "alt-02",
    title: "Storm Surge Inundation Alert for Konark - Astaranga",
    message: "Tidal surge of 1.5 - 2.0 meters forecast during 17:00 - 21:00 high tide. Evacuation to cyclonic shelters mandatory.",
    severity: "high",
    hazardType: "cyclone",
    issuedAt: "2026-10-08T12:45:00Z",
    source: "India Meteorological Department (IMD)",
  },
  {
    id: "alt-03",
    title: "Drinking Water Contamination Advisory",
    message: "Piped water pipeline in Puri South Zone compromised by seawater intrusion. Consume only halogen-treated or bottled supplies.",
    severity: "medium",
    hazardType: "flood",
    issuedAt: "2026-10-08T11:00:00Z",
    source: "Public Health Engineering Dept",
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "ins-01",
    title: "Predictive Breach Likelihood: Daya Embankment km 14.2",
    confidencePct: 91.8,
    impactSummary: "Breach within 3 hours will trap 14,200 residents in 4 villages within Brahmagiri block.",
    recommendedAction: "Divert 2 NDRF teams with 4 Gemini boats from Pipili depot now; initiate megaphone sirens in Ward 6.",
    priority: "critical",
  },
  {
    id: "ins-02",
    title: "Hospital Bed Exhaustion Forecast: DHH Puri",
    confidencePct: 88.5,
    impactSummary: "ICU bed occupancy projected to reach 100% capacity in 4 hours 30 mins.",
    recommendedAction: "Establish tele-triage link with Pipili SDH and redirect non-ventilator trauma cases to Bhubaneswar AIIMS corridor.",
    priority: "high",
  },
  {
    id: "ins-03",
    title: "Optimal Safe Evacuation Corridor Calculated",
    confidencePct: 96.0,
    impactSummary: "Marine Drive is 100% impassable; NH-316 Northward bypass remains free of inundation risk for the next 18 hours.",
    recommendedAction: "Switch digital expressway VMS displays to route all civilian traffic via Sakhigopal - Satyabadi junction.",
    priority: "medium",
  },
];

export const MOCK_CASCADE_GRAPH: CascadeGraph = {
  nodes: [
    { id: "c1", label: "Cyclone Landfall (135 km/h)", type: "trigger", status: "active", impactScore: 95 },
    { id: "c2", label: "Power Grid Substation 132kV Flooded", type: "infrastructure", status: "active", impactScore: 88 },
    { id: "c3", label: "Cellular Tower Blackout (24 Towers)", type: "telecom", status: "active", impactScore: 79 },
    { id: "c4", label: "Water Filtration Plant Shuts Down", type: "utility", status: "warning", impactScore: 82 },
    { id: "c5", label: "District Hospital Diesel Generator at 22%", type: "healthcare", status: "critical", impactScore: 92 },
    { id: "c6", label: "Marine Drive Bridge Approach Scour", type: "transport", status: "active", impactScore: 85 },
  ],
  edges: [
    { source: "c1", target: "c2", probabilityPct: 98, lagHours: 1 },
    { source: "c2", target: "c3", probabilityPct: 90, lagHours: 0.5 },
    { source: "c2", target: "c4", probabilityPct: 85, lagHours: 2 },
    { source: "c2", target: "c5", probabilityPct: 94, lagHours: 3 },
    { source: "c1", target: "c6", probabilityPct: 78, lagHours: 4 },
  ],
};
